version: '3.8'

# Los volúmenes se comparten en el scope del docker-compose
# Si queremos unos volúmenes válidos para todo el entorno de 
# docker, deberemos crearlos manualmente con "docker create volume"

volumes:
  jenkins-docker-certs:
  jenkins-data:

services:
  jenkins-docker:
    image: docker:dind
    ports:
      - "2376:2376"
    volumes:
      - jenkins-docker-certs:/certs/client:cached
      - jenkins-data:/var/jenkins_home:cached
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    privileged: true

  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-docker-certs:/certs/client:cached
      - jenkins-data:/var/jenkins_home:cached
    networks:
      jenkins:
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      JAVA_OPTS: "-Xmx2048m -Djava.awt.headless=true"


networks:
  jenkins:
